export function resetViewState(setters) {
  setters.setTrainers([])
  setters.setRoutines([])
  setters.setRoutinesTitle('Routines')
  setters.setTrainerRoutinesById({})
  setters.setShowTrainers(false)
  setters.setShowRoutines(false)
  setters.setShowTodayRoutine(false)
  setters.setShowTrainerClients(false)
  setters.setTrainerClients([])
  setters.setTodayRoutine(null)
  setters.setTodayRoutineTrainer(null)
  setters.setTodayRoutineError('')
  setters.setCreateRole('Client')
  setters.setCreateFullName('')
  setters.setCreateEmail('')
  setters.setCreateUserName('')
  setters.setCreatePassword('')
  setters.setCreateUserMessage('')
  setters.setRoutineName('')
  setters.setRoutineDescription('')
  setters.setRoutineTrainerId('')
  setters.setCreateRoutineMessage('')
  setters.setAssignClientIdByRoutineId({})
  setters.setAssignRoutineMessage('')
  setters.setAssignTrainerClientIdByTrainerId({})
  setters.setAssigningTrainerByTrainerId('')
  setters.setAssignTrainerMessage('')
}

export function clearGlobalMessages(setters) {
  setters.setError('')
  setters.setCreateUserMessage('')
  setters.setCreateRoutineMessage('')
  setters.setAssignRoutineMessage('')
}
